import React from 'react';

import styles from './index.module.scss';

const Component = () => {
  return (
    <div className={styles.icontFont}>
      <div className={styles.title}>
        <div className={styles.leftContent}>
          <div className={styles.rectangle1}>
            <img src="../image/mef2yvu3-qfwfxbu.svg" className={styles.icon} />
          </div>
          <p className={styles.headerIcon}>Icon Font</p>
        </div>
        <div className={styles.logo}>
          <div className={styles.elements}>
            <div className={styles.element}>
              <div className={styles.circle} />
            </div>
            <div className={styles.element2}>
              <div className={styles.circle2} />
              <div className={styles.circle3} />
            </div>
            <div className={styles.element3}>
              <div className={styles.circle4} />
              <div className={styles.circle5} />
              <div className={styles.circle6} />
            </div>
          </div>
          <p className={styles.ohj3}>
            <span className={styles.ohj}>brix templates</span>
            <span className={styles.ohj2}>&nbsp;</span>
          </p>
        </div>
      </div>
      <div className={styles.iconFont}>
        <div className={styles.grid2}>
          <p className={styles.subtitle}>Line icons rounded</p>
          <div className={styles.grid}>
            <img
              src="../image/mef2yvu3-7qi1qiv.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-29tvirk.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-nitukmc.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-ef15js1.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-72ydzzb.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-vhif7ju.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-pzgljqy.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-3sj9ws6.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-scwtkws.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-318l3en.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-hivm2sb.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-fqs45c6.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-6prnkz8.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-18f4czu.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-3rcznhp.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-d6i7yuu.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-c9zxbsd.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-bxkhtra.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-g1q3pfc.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-698ca08.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-suuw5d8.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-7xtv1kz.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-lvn2n3m.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-04xmc7g.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-has8sg3.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-s1q0ayx.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-p27dhxt.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-snfx3f1.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-761ihzy.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu3-psu8zlb.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-2psqbqc.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-hlakap6.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-ipyvjnu.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-ghnmshu.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-qdrvakk.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-mm98a9r.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-bycf8qp.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-uysqrc1.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-f3v4nre.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-2weshrc.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-rhyw2im.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-99cmd3k.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-gptbd1z.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-v2itffp.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-ekfvk2b.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-jv4m8a8.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-tq73czf.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-7dpvt9g.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-vvilj5h.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-hxmdej1.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-acarxuo.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-44bm5rz.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-sze9q44.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-ci1vzm4.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-qyijknf.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-emr9yto.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-4xta4gp.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-sjc58lv.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-6jcpakq.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-uqebhk0.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-qs94gpp.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-sixjgyu.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-4jhlj7w.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-9n3hh32.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-fh6oq92.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-f1hu17t.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-ie9yyzk.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-h67xxwr.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-1e04fz6.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-kr51jon.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-9ukkctg.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-a5a1lyq.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-7ogmqni.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-7bp06kt.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-ypgstce.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-df68sdd.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-zgp2i3a.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-f1bly7m.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-1957vpt.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-qlif2q1.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-cdpvswe.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-n586ljl.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-ca8ra0f.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-d4gidry.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-qhnfzj9.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-a8tn9td.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-arwpgji.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-0cfpo6x.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-1vr1pv6.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-161ht5w.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-k94z2py.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-2ny6q1g.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-xfcyq14.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-hccingd.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-rvrxub2.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-b7vb8ix.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-em1z27e.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-d8bwir2.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-yn65ysq.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-411lino.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-wkmepk3.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-b5ekg04.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-zguditn.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-74ospd5.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-gof3ns0.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-utyjkic.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-ftrr7qh.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-sgtol8z.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-kijhgyu.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-0it1nra.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-ejyr8co.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-khaebc5.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-dtyonnd.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-m4bg2n4.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-408mcho.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-8z28438.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-x07qgdl.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-1j67aky.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-52p265j.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-oc65qo6.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-5ukqljn.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-c5krfj5.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-v04xnhb.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-hpfnnuj.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-i2y7t1n.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-h047x9n.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-qfd06il.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-ny9fv1c.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-39evbl1.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-is2dv1s.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-igfoskv.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-04ajqhi.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-21u2jvx.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-zjccesa.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-9xwuhkp.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-70724rw.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-5uh9ey9.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-jew57n8.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-sme3sz7.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-3i8gq2b.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-3onk7tu.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-8p2xh1c.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-1xp84ks.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-oiloal7.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-cnywt83.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-8bkjdi7.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-03mu7ht.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-eps98ub.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-tolp49y.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-pg2zt6e.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-iw94cnf.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-ny9z0fw.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-yedkyic.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-44he8nh.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-vr4x8o9.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-4at8ya3.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-rtonqnr.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-iyxmqxp.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-sz953xa.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-lypccvj.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-egqq2tg.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-2ghp2az.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-v5hyod1.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-1t9xplh.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-zcplcas.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-gm8t3q2.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-kt5s985.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-qh9ew3n.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-zuc1m9f.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-28hn5pu.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-amdo4d4.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-l5l9paz.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-px8qkvk.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-jbjjat7.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-6jxqbs8.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-y1adnng.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-7799w1t.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-qyutsw7.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-7pdbx55.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-k4rsrod.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-fhgguzx.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-641zdgg.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-562prx0.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-gfizei7.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-sv0xvil.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-1rfgvwi.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-wdjkqdv.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-rktv0fv.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-7p7lbss.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-mx9o5b4.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-4ihuzr4.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-n0pu4sn.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-hpwkkca.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-md9ja3o.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-mzto0hg.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-hiyklj5.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-ddy3o8v.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-houb94s.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-lbo37kf.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-6ddswgk.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-zshloed.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-pjsn3ok.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-5qft7l8.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-rr6fusm.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-euchw0b.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-qw9ihoh.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-fhd1r6w.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-rdxyg7t.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-tm9hnjw.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-5bkfpp7.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-lekpn04.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-yodefnw.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-5w9h3i0.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-c51o4wn.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-u32scry.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-qevfkj6.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-am9luju.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-hgczhcf.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-59oxj3v.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-nwrrja3.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-f2g0y3y.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-w65jg3d.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-wwkd6ja.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-3rug1lw.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu4-4vwjl6r.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu5-somab9h.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu5-lyotwze.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu5-qw3zucb.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu5-pka78wl.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu5-ev3hxrv.svg"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="../image/mef2yvu5-6n7thfu.svg"
              className={styles.lineRoundedArrowDown}
            />
            <div className={styles.containerArrow}>
              <img
                src="https://via.placeholder.com/10x10"
                className={styles.lineRoundedArrowRigt}
              />
            </div>
            <img
              src="https://via.placeholder.com/18x18"
              className={styles.lineRoundedUserV2}
            />
          </div>
        </div>
        <div className={styles.wrapper}>
          <p className={styles.subtitle}>Filled icons</p>
          <div className={styles.iconsGrid}>
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
            <img
              src="https://via.placeholder.com/20x20"
              className={styles.lineRoundedArrowDown}
            />
          </div>
        </div>
      </div>
      <div className={styles.grid4}>
        <p className={styles.subtitle}>Social Icons</p>
        <div className={styles.grid3}>
          <div className={styles.socialMediaIconSquar}>
            <div className={styles.socialMediaFacebookC}>
              <img
                src="https://via.placeholder.com/16x16"
                className={styles.icon2}
              />
            </div>
            <div className={styles.socialMediaTwitterXc}>
              <img
                src="https://via.placeholder.com/16x16"
                className={styles.icon2}
              />
            </div>
            <div className={styles.socialMediaInstagram}>
              <img
                src="https://via.placeholder.com/16x16"
                className={styles.icon2}
              />
            </div>
            <div className={styles.socialMediaLinkedInC}>
              <img
                src="https://via.placeholder.com/16x16"
                className={styles.icon2}
              />
            </div>
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.socialMediaYouTubeCo}
            />
            <img
              src="https://via.placeholder.com/24x24"
              className={styles.aASocialMediaIconSqu}
            />
          </div>
        </div>
      </div>
    </div>
  );
}

export default Component;
