version: "3.9"

services:
  backend:
    image: video_jianji:v1
    container_name: video_backend
    working_dir: /opt/lan_video-hun-jian-feng-branch/backend_py
    command: bash -c "source /etc/profile && cd /opt/lan_video-hun-jian-feng-branch/backend_py && source .venv/bin/activate && uvicorn main:app --reload --host 0.0.0.0"
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: video_jianji:v1
    container_name: video_frontend
    working_dir: /opt/lan_video-hun-jian-feng-branch/frontend
    command: bash -c "source /etc/profile && cd /opt/lan_video-hun-jian-feng-branch/frontend && npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
